[project]
name = "deepseek-r1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=2.5.43",
    "dspy-ai>=2.5.43",
    "requests>=2.32.3",
]
